default: &default
  adapter: postgresql
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  timeout: 5000

development:
  <<: *default
  encoding: unicode
  database: ireport_development


# test:
#   <<: *default
#   database: db/test.sqlite3

production:
  <<: *default
  prepared_statements: false
